# Generated by Django 3.2.3 on 2021-05-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PontoTuristico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
