# Generated by Django 3.2.3 on 2021-05-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avaliacoes', '0001_initial'),
        ('PontoTuristico', '0004_pontoturistico_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='Avaliacoes',
            field=models.ManyToManyField(to='Avaliacoes.Avaliacao'),
        ),
    ]
